### ISSUE TITLE
TL-3: if __name__ == '__main__'

### ISSUE THREAD

**Issue by tomlue** [biobricks-ai/adrecs#3]
In your dvc.yaml you have:

```
stages:
  fetch_data:
    cmd: python 01_adrecs.py
    deps:
      - ./stages/01_adrecs.py
    outs:
      - data/
```

Typically I would make this:

```
stages:
  fetch_data:
    cmd: python stages/01_adrecs.py
    deps:
      - ./stages/01_adrecs.py
    outs:
      - data/
```

dvc runs with the project root as the working directory. 

Also, when you run scripts this way you don't need to do the 

```
if __name__ == '__main__':
```

thing. 

I think it is fine if you think there is some advantage, but it is not a python package so you aren't really building classes and a main python script.
